In [3]:
!python -m pip install openai pandas python-dotenv

Collecting openai
  Downloading openai-2.32.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: pandas in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (3.0.2)
Collecting python-dotenv
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from openai) (4.13.0)
Collecting distro<2,>=1.7.0 (from openai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.14.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting pydantic<3,>=1.9.0 (from openai)
  Downloading pydantic-2.13.3-py3-none-any.whl.metadata (108 kB)
Collecting sniffio (from openai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>4 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from anyio<5,>=3.5.0->openai) (3.13)
Requirement already satisfied: certifi in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=1.9.0->openai)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.3 (from pydantic<3,>=1.9.0->openai)
  Downloading pydantic_core-2.46.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=1.9.0->openai)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy>=2.3.3 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openai-2.32.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 30.6 MB/s  0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading jiter-0.14.0-cp314-cp314-macosx_11_0_arm64.whl (315 kB)
Downloading pydantic-2.13.3-py3-none-any.whl (471 kB)
Downloading pydantic_core-2.46.3-cp314-cp314-macosx_11_0_arm64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 36.4 MB/s  0:00:00
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: typing-inspection, sniffio, python-dotenv, pydantic-core, jiter, distro, annotated-types, pydantic, openai
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [openai]2m8/9 [openai]c]
Successfully installed annotated-types-0.7.0 distro-1.9.0 jiter-0.14.0 openai-2.32.0 pydantic-2.13.3 pydantic-core-2.46.3 python-dotenv-1.2.2 sniffio-1.3.1 typing-inspection-0.4.2

In [4]:
import os
import json
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

In [5]:
PROJECT_ROOT = Path("/Users/apple/Desktop/UCL/skills/python3")
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
API_OUTPUTS_DIR = PROJECT_ROOT / "data" / "api_outputs"

API_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

print("PROCESSED_DIR exists?", PROCESSED_DIR.exists())
print("API_OUTPUTS_DIR exists?", API_OUTPUTS_DIR.exists())

PROCESSED_DIR exists? True
API_OUTPUTS_DIR exists? True

In [6]:
all_df = pd.read_csv(PROCESSED_DIR / "texts_with_clusters.csv")
print(all_df.shape)
all_df.head()

(1793, 12)

,dataset,source,page_title,text_id,raw_text,cleaned_text,word_count,dataset_label,cluster,pca_x,pca_y,cluster_name
0,landforms,wikipedia,Desert,Desert_0,A desert is a landscape where little precipita...,A desert is a landscape where little precipita...,91,landforms,5,0.371352,0.011644,atmospheric_abstract
1,landforms,wikipedia,Desert,Desert_1,Deserts are formed by weathering processes as ...,Deserts are formed by weathering processes as ...,218,landforms,5,0.358664,0.273669,atmospheric_abstract
2,landforms,wikipedia,Desert,Desert_2,Plants and animals living in the desert need s...,Plants and animals living in the desert need s...,147,landforms,5,0.173692,-0.226674,atmospheric_abstract
3,landforms,wikipedia,Desert,Desert_3,People have struggled to live in deserts and t...,People have struggled to live in deserts and t...,151,landforms,5,0.042568,-0.075830,atmospheric_abstract
4,landforms,wikipedia,Desert,Desert_4,English desert and its Romance cognates (inclu...,English desert and its Romance cognates (inclu...,131,landforms,5,0.096850,-0.023956,atmospheric_abstract

In [7]:
cluster_examples = {}

for c in sorted(all_df["cluster"].unique()):
    sub = all_df[all_df["cluster"] == c].copy()

    cluster_name = sub["cluster_name"].iloc[0] if "cluster_name" in sub.columns else f"cluster_{c}"

    examples = sub["cleaned_text"].dropna().astype(str).head(8).tolist()

    cluster_examples[str(c)] = {
        "cluster_id": int(c),
        "cluster_name": cluster_name,
        "dataset_distribution": sub["dataset_label"].value_counts().to_dict(),
        "examples": examples
    }

cluster_examples

{'0': {'cluster_id': 0,
  'cluster_name': 'dry_exposed',
  'dataset_distribution': {'landforms': 146, 'climate': 11, 'gutenberg': 3},
  'examples': ['Cave-inhabiting animals are often categorized as troglobites (cave-limited species), troglophiles (species that can live their entire lives in caves, but also occur in other environments), trogloxenes (species that use caves, but cannot complete their life cycle fully in caves) and accidentals (animals not in one of the previous categories). Some authors use separate terminology for aquatic forms (for example, stygobites, stygophiles, and stygoxenes).',
   'Of these animals, the troglobites are perhaps the most unusual organisms. Troglobitic species often show a number of characteristics, termed troglomorphic, associated with their adaptation to subterranean life. These characteristics may include a loss of pigment (often resulting in a pale or white coloration), a loss of eyes (or at least of optical functionality), an elongation of appendages, and an enhancement of other senses (such as the ability to sense vibrations in water). Aquatic troglobites (or stygobites), such as the endangered Alabama cave shrimp, live in bodies of water found in caves and get nutrients from detritus washed into their caves and from the feces of bats and other cave inhabitants. Other aquatic troglobites include cave fish, and cave salamanders such as the olm and the Texas blind salamander.',
   'Because of the fragility of cave ecosystems, and the fact that cave regions tend to be isolated from one another, caves harbor a number of endangered species, such as the Tooth cave spider, liphistius trapdoor spider, and the gray bat.',
   'Coral belongs to the class Anthozoa in the animal phylum Cnidaria, which includes sea anemones and jellyfish. Unlike sea anemones, corals secrete hard carbonate exoskeletons that support and protect the coral. Most reefs grow best in warm, shallow, clear, sunny, and agitated water. Coral reefs first appeared 485 million years ago, at the dawn of the Early Ordovician, displacing the microbial and sponge reefs of the Cambrian.',
   "Sometimes called rainforests of the sea, shallow coral reefs form some of Earth's most diverse ecosystems. They occupy less than 0.1% of the world's ocean area, about half the area of France. Yet, they provide a home for at least 25% of all marine species, including fish, mollusks, worms, crustaceans, echinoderms, sponges, tunicates and other cnidarians. Coral reefs flourish in ocean waters that provide few nutrients. They are most commonly found at shallow depths in tropical waters, but deep water and cold water coral reefs exist on smaller scales in other areas.",
   'Shallow tropical coral reefs have declined by 50% since 1950, partly because they are sensitive to water conditions. They are under threat from excess nutrients (nitrogen and phosphorus), rising ocean heat content and acidification, overfishing (e.g., from blast fishing, cyanide fishing, spearfishing on scuba), sunscreen use, and harmful land-use practices, including runoff and seeps (e.g., from injection wells and cesspools).',
   'Coral reefs deliver ecosystem services for tourism, fisheries, and shoreline protection. The annual global economic value of coral reefs has been estimated at anywhere from US$30–375 billion (1997 and 2003 estimates) to US$2.7 trillion (a 2020 estimate) to US$9.9 trillion (a 2014 estimate).',
   'Most coral reefs were formed after the Last Glacial Period when melting ice caused sea level to rise and flood continental shelves. Most coral reefs are less than 10,000 years old. As communities established themselves, the reefs grew upward, keeping pace with rising sea levels. Reefs that rose too slowly could become drowned, without sufficient light. Coral reefs are also found in the deep sea away from continental shelves, around oceanic islands and atolls. The majority of these islands are volcanic in origin. Others have tectonic origins where plate movements lifted the deep ocean floor.']},
 '1': {'cluster_id': 1,
  'cluster_name': 'frozen_quiet',
  'dataset_distribution': {'gutenberg': 473, 'landforms': 11, 'climate': 8},
  'examples': ['People have been living in deserts for millennia. Many, such as the Bushmen in the Kalahari, the Aborigines in Australia and various tribes of North American Indians, were originally hunter-gatherers. They developed skills in the manufacture and use of weapons, animal tracking, finding water, foraging for edible plants and using the things they found in their natural environment to supply their everyday needs. Their self-sufficient skills and knowledge were passed down through the generations by word of mouth. Other cultures developed a nomadic way of life as herders of sheep, goats, cattle, camels, yaks, llamas or reindeer. They travelled over large areas with their herds, moving to new pastures as seasonal and erratic rainfall encouraged new plant growth. They took with them their tents made of cloth or skins draped over poles and their diet included milk, blood and sometimes meat.',
   'The desert nomads were also traders. The Sahara is a very large expanse of land stretching from the Atlantic rim to Egypt. Trade routes were developed linking the Sahel in the south with the fertile Mediterranean region to the north and large numbers of camels were used to carry valuable goods across the desert interior. The Tuareg were traders and the transported goods traditionally included slaves, ivory and gold going northwards and salt going southwards. Berbers with knowledge of the region were employed to guide the caravans between the various oases and wells. Several million slaves may have been taken northwards across the Sahara between the 8th and 18th centuries. Traditional means of overland transport declined with the advent of motor vehicles, shipping and air freight, but caravans still travel along routes between Agadez and Bilma and between Timbuktu and Taoudenni carrying salt from the interior to desert-edge communities.',
   'The Arabs were probably the first organized force to conduct successful battles in the desert. By knowing back routes and the locations of oases and by utilizing camels, Muslim Arab forces were able to successfully overcome both Roman and Persian forces in the period 600 to 700 AD during the expansion of the Islamic caliphate.',
   "Many centuries later, both world wars saw fighting in the desert. In the First World War, the Ottoman Turks were engaged with the British regular army in a campaign that spanned the Arabian Peninsula. The Turks were defeated by the British, who had the backing of irregular Arab forces that were seeking to revolt against the Turks in the Hejaz, made famous in T.E. Lawrence's book Seven Pillars of Wisdom.",
   'In the Second World War, the Western Desert Campaign began in Italian Libya. Warfare in the desert offered great scope for tacticians to use the large open spaces without the distractions of casualties among civilian populations. Tanks and armoured vehicles were able to travel large distances unimpeded and land mines were laid in large numbers. However, the size and harshness of the terrain meant that all supplies needed to be brought in from great distances. The victors in a battle would advance and their supply chain would necessarily become longer, while the defeated army could retreat, regroup and resupply. For these reasons, the front line moved back and forth through hundreds of kilometers as each side lost and regained momentum. Its most easterly point was at El Alamein in Egypt, where the Allies decisively defeated the Axis forces in 1942.',
   "There is an extensive literature on the subject of deserts. An early historical account is that of Marco Polo (c. 1254–1324), who travelled through Central Asia to China, crossing a number of deserts in his twenty four year trek. Some accounts give vivid descriptions of desert conditions, though often accounts of journeys across deserts are interwoven with reflection, as is the case in Charles Montagu Doughty's major work, Travels in Arabia Deserta (1888). Antoine de Saint-Exupéry described both his flying and the desert in Wind, Sand and Stars, and Gertrude Bell travelled extensively in the Arabian desert in the early part of the 20th century, becoming an expert on the subject, writing books and advising the British government on dealing with the Arabs. Another woman explorer was Freya Stark, who travelled alone in the Middle East, visiting Turkey, Arabia, Yemen, Syria, Persia and Afghanistan, writing over twenty books on her experiences. The German naturalist Uwe George spent several years living in deserts, recording his experiences and research in his 1976 book, In the Deserts of this Earth.",
   'The American poet Robert Frost expressed his bleak thoughts in his poem, Desert Places (1933), which ends with the stanza "They cannot scare me with their empty spaces / Between stars – on stars where no human race is. / I have it in me so much nearer home / To scare myself with my own desert places.',
   'Saints associated with the desert include Anthony the Great, also known as "Anthony of the Desert". Pope Benedict XVI linked the metaphorical existence of "internal deserts" with physical and social deserts in his homily inaugurating his papacy: "The external deserts in the world are growing, because the internal deserts have become so vast".']},
 '2': {'cluster_id': 2,
  'cluster_name': 'lush_dense',
  'dataset_distribution': {'climate': 194, 'landforms': 182, 'gutenberg': 4},
  'examples': ['Deserts occupy about one third of Earth\'s land surface. Bottomlands may be salt-covered flats. Eolian processes are major factors in shaping desert landscapes. Polar deserts (also seen as "cold deserts") have similar features, except the main form of precipitation is snow rather than rain. Antarctica is the world\'s largest cold desert (composed of about 98% thick continental ice sheet and 2% barren rock). Some of the barren rock is to be found in the so-called Dry Valleys of Antarctica that almost never get snow, which can have ice-encrusted saline lakes that suggest evaporation far greater than the rare snowfall due to the strong katabatic winds that even evaporate ice.',
   'Lakes may form in basins where there is sufficient precipitation or meltwater from glaciers above. They are usually shallow and saline, and wind blowing over their surface can cause stress, moving the water over nearby low-lying areas. When the lakes dry up, they leave a crust or hardpan behind. This area of deposited clay, silt or sand is known as a playa. The deserts of North America have more than one hundred playas, many of them relics of Lake Bonneville which covered parts of Utah, Nevada and Idaho during the last ice age when the climate was colder and wetter. These include the Great Salt Lake, Utah Lake, Sevier Lake and many dry lake beds. The smooth flat surfaces of playas have been used for attempted vehicle speed records at Black Rock Desert and Bonneville Speedway and the United States Air Force uses Rogers Dry Lake in the Mojave Desert as runways for aircraft and the Space Shuttle.',
   'Montane deserts are arid places with a very high altitude; the most prominent example is found north of the Himalayas, in the Kunlun Mountains and the Tibetan Plateau. Many locations within this category have elevations exceeding 3,000 m (9,800 ft) and the thermal regime can be hemiboreal. These places owe their profound aridity (the average annual precipitation is often less than 40 mm or 1.5 in) to being very far from the nearest available sources of moisture and are often in the lee of mountain ranges. Montane deserts are normally cold, or may be scorchingly hot by day and very cold by night as is true of the northeastern slopes of Mount Kilimanjaro.',
   'Polar deserts such as McMurdo Dry Valleys remain ice-free because of the dry katabatic winds that flow downhill from the surrounding mountains. Former desert areas presently in non-arid environments, such as the Sandhills in Nebraska, are known as paleodeserts. In the Köppen climate classification system, deserts are classed as BWh (hot desert) or BWk (temperate desert). In the Thornthwaite climate classification system, deserts would be classified as arid megathermal climates.',
   'The McMurdo dry valleys of Antarctica, which lack water (whether rain, ice, or snow) much like a non-polar desert and even have such desert features as hypersaline lakes and intermittent streams that resemble (except for being frozen at their surfaces) hot or cold deserts for extreme aridity and lack of precipitation of any kind. Extreme winds and not seasonal heat desiccate these nearly-lifeless terrains.',
   "Deserts usually have a large diurnal and seasonal temperature range, with high daytime temperatures falling sharply at night. The diurnal range may be as much as 20 to 30 °C (36 to 54 °F) and the rock surface experiences even greater temperature differentials. During the day the sky is usually clear and most of the sun's radiation reaches the ground, but as soon as the sun sets, the desert cools quickly by radiating heat into space. In hot deserts, the temperature during daytime can exceed 45 °C (113 °F) in summer and plunge below freezing point at night during winter.",
   'Such large temperature variations have a destructive effect on the exposed rocky surfaces. The repeated fluctuations put a strain on exposed rock and the flanks of mountains crack and shatter. Fragmented strata slide down into the valleys where they continue to break into pieces due to the relentless sun by day and chill by night. Successive strata are exposed to further weathering. The relief of the internal pressure that has built up in rocks that have been underground for aeons can cause them to shatter. Exfoliation also occurs when the outer surfaces of rocks split off in flat flakes. This is believed to be caused by the stresses put on the rock by repeated thermal expansions and contractions which induces fracturing parallel to the original surface. Chemical weathering processes probably play a more important role in deserts than was previously thought. The necessary moisture may be present in the form of dew or mist. Ground water may be drawn to the surface by evaporation and the formation of salt crystals may dislodge rock particles as sand or disintegrate rocks by exfoliation. Shallow caves are sometimes formed at the base of cliffs by this means.',
   'As the desert mountains decay, large areas of shattered rock and rubble occur. The process continues and the end products are either dust or sand. Dust is formed from solidified clay or volcanic deposits whereas sand results from the fragmentation of harder granites, limestone and sandstone. There is a certain critical size (about 0.5 mm) below which further temperature-induced weathering of rocks does not occur and this provides a minimum size for sand grains.']},
 '3': {'cluster_id': 3,
  'cluster_name': 'flowing_unstable',
  'dataset_distribution': {'gutenberg': 209, 'landforms': 10, 'climate': 3},
  'examples': ["A canyon (from Spanish cañón; archaic British English spelling: cañon), gorge or chasm, is a deep cleft between escarpments or cliffs resulting from weathering and the erosive activity of a river over geologic time scales. Rivers have a natural tendency to cut through underlying surfaces, eventually wearing away rock layers as sediments are removed downstream. A river bed will gradually reach a baseline elevation, which is the same elevation as the body of water into which the river drains. The processes of weathering and erosion will form canyons when the river's headwaters and estuary are at significantly different elevations, particularly through regions where softer rock layers are intermingled with harder layers more resistant to weathering.",
   "A canyon may also refer to a rift between two mountain peaks, such as those in ranges including the Rocky Mountains, the Alps, the Himalayas or the Andes. Usually, a river or stream carves out such splits between mountains. Examples of mountain-type canyons are Provo Canyon in Utah or Yosemite Valley in California's Sierra Nevada. Canyons within mountains, or gorges that have an opening on only one side, are called box canyons. Slot canyons are very narrow canyons that often have smooth walls.",
   'The word canyon is Spanish in origin (cañón, pronounced [kaˈɲon]), with the same meaning. The word canyon is generally used in North America, while the words gorge and ravine (French in origin) are used in Europe and Oceania, though gorge and ravine are also used in some parts of North America. In the United States, place names generally use canyon in the southwest (due to their proximity to Spanish-speaking Mexico) and gorge in the northeast (which is closer to French Canada), with the rest of the country graduating between these two according to geography. In Canada, a gorge is usually narrow while a ravine is more open and often wooded. The military-derived word defile is occasionally used in the United Kingdom. In South Africa, kloof (in Krantzkloof Nature Reserve) is used along with canyon (as in Blyde River Canyon) and gorge (in Oribi Gorge).',
   'Sometimes large rivers run through canyons as the result of gradual geological uplift. These are called entrenched rivers, because they are unable to easily alter their course. In the United States, the Colorado River in the Southwest and the Snake River in the Northwest are two examples of tectonic uplift.',
   'A box canyon is a small canyon that is generally shorter and narrower than a river canyon, with steep walls on three sides, allowing access and egress only through the mouth of the canyon. Box canyons were frequently used in the western United States as convenient corrals, with their entrances fenced.',
   'The Yarlung Tsangpo Grand Canyon (or Tsangpo Canyon), along the Yarlung Tsangpo River in Tibet, China, is regarded by some as the deepest canyon on Earth at 5,500 metres (18,000 ft). It is slightly longer than Grand Canyon in the United States. Others consider the Kali Gandaki Gorge in midwest Nepal to be the deepest canyon, with a 6,400-metre (21,000 ft) difference between the level of the river and the peaks surrounding it.',
   "Grand Canyon of northern Arizona in the United States, with an average depth of 1,600 metres (5,200 ft) and a volume of 4.17 trillion cubic metres (147 trillion cubic feet), is one of the world's largest canyons. It was among the 28 finalists of the New 7 Wonders of Nature worldwide poll. (Some referred to it as one of the seven natural wonders of the world.)",
   "Some canyons have notable cultural significance. Evidence of archaic humans has been discovered in Africa's Olduvai Gorge. In the southwestern United States, canyons are important archeologically because of the many cliff-dwellings built in such areas, largely by the ancient Pueblo people who were their first inhabitants."]},
 '4': {'cluster_id': 4,
  'cluster_name': 'rocky_vertical',
  'dataset_distribution': {'gutenberg': 205, 'landforms': 27, 'climate': 2},
  'examples': ['Other xerophytic plants have developed similar strategies by a process known as convergent evolution. They limit water loss by reducing the size and number of stomata, by having waxy coatings and hairy or tiny leaves. Some are deciduous, shedding their leaves in the driest season, and others curl their leaves up to reduce transpiration. Others, such as aloes, store water in succulent leaves or stems or in fleshy tubers.',

In [8]:
with open(API_OUTPUTS_DIR / "cluster_examples.json", "w", encoding="utf-8") as f:
    json.dump(cluster_examples, f, ensure_ascii=False, indent=2)

print("Saved:", API_OUTPUTS_DIR / "cluster_examples.json")

Saved: /Users/apple/Desktop/UCL/skills/python3/data/api_outputs/cluster_examples.json

In [ ]:
load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
print("API key loaded?", OPENAI_API_KEY is not None)

In [9]:
!python -m pip install python-dotenv

Requirement already satisfied: python-dotenv in /Users/apple/Desktop/UCL/skills/python3/.venv/lib/python3.14/site-packages (1.2.2)

In [10]:
import os
from dotenv import load_dotenv
from pathlib import Path

In [11]:
PROJECT_ROOT = Path("/Users/apple/Desktop/UCL/skills/python3")
load_dotenv(PROJECT_ROOT / ".env")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
print("API key loaded?", OPENAI_API_KEY is not None)

API key loaded? True

In [12]:
from openai import OpenAI

client = OpenAI(api_key=OPENAI_API_KEY)
print("client created")

client created

In [13]:
import pandas as pd
from pathlib import Path
import json

PROJECT_ROOT = Path("/Users/apple/Desktop/UCL/skills/python3")
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
API_OUTPUTS_DIR = PROJECT_ROOT / "data" / "api_outputs"

API_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

all_df = pd.read_csv(PROCESSED_DIR / "texts_with_clusters.csv")
print(all_df.shape)
print(all_df.columns.tolist())
all_df.head()

(1793, 12)
['dataset', 'source', 'page_title', 'text_id', 'raw_text', 'cleaned_text', 'word_count', 'dataset_label', 'cluster', 'pca_x', 'pca_y', 'cluster_name']

,dataset,source,page_title,text_id,raw_text,cleaned_text,word_count,dataset_label,cluster,pca_x,pca_y,cluster_name
0,landforms,wikipedia,Desert,Desert_0,A desert is a landscape where little precipita...,A desert is a landscape where little precipita...,91,landforms,5,0.371352,0.011644,atmospheric_abstract
1,landforms,wikipedia,Desert,Desert_1,Deserts are formed by weathering processes as ...,Deserts are formed by weathering processes as ...,218,landforms,5,0.358664,0.273669,atmospheric_abstract
2,landforms,wikipedia,Desert,Desert_2,Plants and animals living in the desert need s...,Plants and animals living in the desert need s...,147,landforms,5,0.173692,-0.226674,atmospheric_abstract
3,landforms,wikipedia,Desert,Desert_3,People have struggled to live in deserts and t...,People have struggled to live in deserts and t...,151,landforms,5,0.042568,-0.075830,atmospheric_abstract
4,landforms,wikipedia,Desert,Desert_4,English desert and its Romance cognates (inclu...,English desert and its Romance cognates (inclu...,131,landforms,5,0.096850,-0.023956,atmospheric_abstract

In [14]:
cluster_examples = {}

for c in sorted(all_df["cluster"].unique()):
    sub = all_df[all_df["cluster"] == c].copy()

    cluster_name = sub["cluster_name"].iloc[0] if "cluster_name" in sub.columns else f"cluster_{c}"

    examples = sub["cleaned_text"].dropna().astype(str).head(8).tolist()

    if "dataset_label" in sub.columns:
        dataset_distribution = sub["dataset_label"].value_counts().to_dict()
    else:
        dataset_distribution = {}

    cluster_examples[str(c)] = {
        "cluster_id": int(c),
        "cluster_name": cluster_name,
        "dataset_distribution": dataset_distribution,
        "examples": examples
    }

cluster_examples

{'0': {'cluster_id': 0,
  'cluster_name': 'dry_exposed',
  'dataset_distribution': {'landforms': 146, 'climate': 11, 'gutenberg': 3},
  'examples': ['Cave-inhabiting animals are often categorized as troglobites (cave-limited species), troglophiles (species that can live their entire lives in caves, but also occur in other environments), trogloxenes (species that use caves, but cannot complete their life cycle fully in caves) and accidentals (animals not in one of the previous categories). Some authors use separate terminology for aquatic forms (for example, stygobites, stygophiles, and stygoxenes).',
   'Of these animals, the troglobites are perhaps the most unusual organisms. Troglobitic species often show a number of characteristics, termed troglomorphic, associated with their adaptation to subterranean life. These characteristics may include a loss of pigment (often resulting in a pale or white coloration), a loss of eyes (or at least of optical functionality), an elongation of appendages, and an enhancement of other senses (such as the ability to sense vibrations in water). Aquatic troglobites (or stygobites), such as the endangered Alabama cave shrimp, live in bodies of water found in caves and get nutrients from detritus washed into their caves and from the feces of bats and other cave inhabitants. Other aquatic troglobites include cave fish, and cave salamanders such as the olm and the Texas blind salamander.',
   'Because of the fragility of cave ecosystems, and the fact that cave regions tend to be isolated from one another, caves harbor a number of endangered species, such as the Tooth cave spider, liphistius trapdoor spider, and the gray bat.',
   'Coral belongs to the class Anthozoa in the animal phylum Cnidaria, which includes sea anemones and jellyfish. Unlike sea anemones, corals secrete hard carbonate exoskeletons that support and protect the coral. Most reefs grow best in warm, shallow, clear, sunny, and agitated water. Coral reefs first appeared 485 million years ago, at the dawn of the Early Ordovician, displacing the microbial and sponge reefs of the Cambrian.',
   "Sometimes called rainforests of the sea, shallow coral reefs form some of Earth's most diverse ecosystems. They occupy less than 0.1% of the world's ocean area, about half the area of France. Yet, they provide a home for at least 25% of all marine species, including fish, mollusks, worms, crustaceans, echinoderms, sponges, tunicates and other cnidarians. Coral reefs flourish in ocean waters that provide few nutrients. They are most commonly found at shallow depths in tropical waters, but deep water and cold water coral reefs exist on smaller scales in other areas.",
   'Shallow tropical coral reefs have declined by 50% since 1950, partly because they are sensitive to water conditions. They are under threat from excess nutrients (nitrogen and phosphorus), rising ocean heat content and acidification, overfishing (e.g., from blast fishing, cyanide fishing, spearfishing on scuba), sunscreen use, and harmful land-use practices, including runoff and seeps (e.g., from injection wells and cesspools).',
   'Coral reefs deliver ecosystem services for tourism, fisheries, and shoreline protection. The annual global economic value of coral reefs has been estimated at anywhere from US$30–375 billion (1997 and 2003 estimates) to US$2.7 trillion (a 2020 estimate) to US$9.9 trillion (a 2014 estimate).',
   'Most coral reefs were formed after the Last Glacial Period when melting ice caused sea level to rise and flood continental shelves. Most coral reefs are less than 10,000 years old. As communities established themselves, the reefs grew upward, keeping pace with rising sea levels. Reefs that rose too slowly could become drowned, without sufficient light. Coral reefs are also found in the deep sea away from continental shelves, around oceanic islands and atolls. The majority of these islands are volcanic in origin. Others have tectonic origins where plate movements lifted the deep ocean floor.']},
 '1': {'cluster_id': 1,
  'cluster_name': 'frozen_quiet',
  'dataset_distribution': {'gutenberg': 473, 'landforms': 11, 'climate': 8},
  'examples': ['People have been living in deserts for millennia. Many, such as the Bushmen in the Kalahari, the Aborigines in Australia and various tribes of North American Indians, were originally hunter-gatherers. They developed skills in the manufacture and use of weapons, animal tracking, finding water, foraging for edible plants and using the things they found in their natural environment to supply their everyday needs. Their self-sufficient skills and knowledge were passed down through the generations by word of mouth. Other cultures developed a nomadic way of life as herders of sheep, goats, cattle, camels, yaks, llamas or reindeer. They travelled over large areas with their herds, moving to new pastures as seasonal and erratic rainfall encouraged new plant growth. They took with them their tents made of cloth or skins draped over poles and their diet included milk, blood and sometimes meat.',
   'The desert nomads were also traders. The Sahara is a very large expanse of land stretching from the Atlantic rim to Egypt. Trade routes were developed linking the Sahel in the south with the fertile Mediterranean region to the north and large numbers of camels were used to carry valuable goods across the desert interior. The Tuareg were traders and the transported goods traditionally included slaves, ivory and gold going northwards and salt going southwards. Berbers with knowledge of the region were employed to guide the caravans between the various oases and wells. Several million slaves may have been taken northwards across the Sahara between the 8th and 18th centuries. Traditional means of overland transport declined with the advent of motor vehicles, shipping and air freight, but caravans still travel along routes between Agadez and Bilma and between Timbuktu and Taoudenni carrying salt from the interior to desert-edge communities.',
   'The Arabs were probably the first organized force to conduct successful battles in the desert. By knowing back routes and the locations of oases and by utilizing camels, Muslim Arab forces were able to successfully overcome both Roman and Persian forces in the period 600 to 700 AD during the expansion of the Islamic caliphate.',
   "Many centuries later, both world wars saw fighting in the desert. In the First World War, the Ottoman Turks were engaged with the British regular army in a campaign that spanned the Arabian Peninsula. The Turks were defeated by the British, who had the backing of irregular Arab forces that were seeking to revolt against the Turks in the Hejaz, made famous in T.E. Lawrence's book Seven Pillars of Wisdom.",
   'In the Second World War, the Western Desert Campaign began in Italian Libya. Warfare in the desert offered great scope for tacticians to use the large open spaces without the distractions of casualties among civilian populations. Tanks and armoured vehicles were able to travel large distances unimpeded and land mines were laid in large numbers. However, the size and harshness of the terrain meant that all supplies needed to be brought in from great distances. The victors in a battle would advance and their supply chain would necessarily become longer, while the defeated army could retreat, regroup and resupply. For these reasons, the front line moved back and forth through hundreds of kilometers as each side lost and regained momentum. Its most easterly point was at El Alamein in Egypt, where the Allies decisively defeated the Axis forces in 1942.',
   "There is an extensive literature on the subject of deserts. An early historical account is that of Marco Polo (c. 1254–1324), who travelled through Central Asia to China, crossing a number of deserts in his twenty four year trek. Some accounts give vivid descriptions of desert conditions, though often accounts of journeys across deserts are interwoven with reflection, as is the case in Charles Montagu Doughty's major work, Travels in Arabia Deserta (1888). Antoine de Saint-Exupéry described both his flying and the desert in Wind, Sand and Stars, and Gertrude Bell travelled extensively in the Arabian desert in the early part of the 20th century, becoming an expert on the subject, writing books and advising the British government on dealing with the Arabs. Another woman explorer was Freya Stark, who travelled alone in the Middle East, visiting Turkey, Arabia, Yemen, Syria, Persia and Afghanistan, writing over twenty books on her experiences. The German naturalist Uwe George spent several years living in deserts, recording his experiences and research in his 1976 book, In the Deserts of this Earth.",
   'The American poet Robert Frost expressed his bleak thoughts in his poem, Desert Places (1933), which ends with the stanza "They cannot scare me with their empty spaces / Between stars – on stars where no human race is. / I have it in me so much nearer home / To scare myself with my own desert places.',
   'Saints associated with the desert include Anthony the Great, also known as "Anthony of the Desert". Pope Benedict XVI linked the metaphorical existence of "internal deserts" with physical and social deserts in his homily inaugurating his papacy: "The external deserts in the world are growing, because the internal deserts have become so vast".']},
 '2': {'cluster_id': 2,
  'cluster_name': 'lush_dense',
  'dataset_distribution': {'climate': 194, 'landforms': 182, 'gutenberg': 4},
  'examples': ['Deserts occupy about one third of Earth\'s land surface. Bottomlands may be salt-covered flats. Eolian processes are major factors in shaping desert landscapes. Polar deserts (also seen as "cold deserts") have similar features, except the main form of precipitation is snow rather than rain. Antarctica is the world\'s largest cold desert (composed of about 98% thick continental ice sheet and 2% barren rock). Some of the barren rock is to be found in the so-called Dry Valleys of Antarctica that almost never get snow, which can have ice-encrusted saline lakes that suggest evaporation far greater than the rare snowfall due to the strong katabatic winds that even evaporate ice.',
   'Lakes may form in basins where there is sufficient precipitation or meltwater from glaciers above. They are usually shallow and saline, and wind blowing over their surface can cause stress, moving the water over nearby low-lying areas. When the lakes dry up, they leave a crust or hardpan behind. This area of deposited clay, silt or sand is known as a playa. The deserts of North America have more than one hundred playas, many of them relics of Lake Bonneville which covered parts of Utah, Nevada and Idaho during the last ice age when the climate was colder and wetter. These include the Great Salt Lake, Utah Lake, Sevier Lake and many dry lake beds. The smooth flat surfaces of playas have been used for attempted vehicle speed records at Black Rock Desert and Bonneville Speedway and the United States Air Force uses Rogers Dry Lake in the Mojave Desert as runways for aircraft and the Space Shuttle.',
   'Montane deserts are arid places with a very high altitude; the most prominent example is found north of the Himalayas, in the Kunlun Mountains and the Tibetan Plateau. Many locations within this category have elevations exceeding 3,000 m (9,800 ft) and the thermal regime can be hemiboreal. These places owe their profound aridity (the average annual precipitation is often less than 40 mm or 1.5 in) to being very far from the nearest available sources of moisture and are often in the lee of mountain ranges. Montane deserts are normally cold, or may be scorchingly hot by day and very cold by night as is true of the northeastern slopes of Mount Kilimanjaro.',
   'Polar deserts such as McMurdo Dry Valleys remain ice-free because of the dry katabatic winds that flow downhill from the surrounding mountains. Former desert areas presently in non-arid environments, such as the Sandhills in Nebraska, are known as paleodeserts. In the Köppen climate classification system, deserts are classed as BWh (hot desert) or BWk (temperate desert). In the Thornthwaite climate classification system, deserts would be classified as arid megathermal climates.',
   'The McMurdo dry valleys of Antarctica, which lack water (whether rain, ice, or snow) much like a non-polar desert and even have such desert features as hypersaline lakes and intermittent streams that resemble (except for being frozen at their surfaces) hot or cold deserts for extreme aridity and lack of precipitation of any kind. Extreme winds and not seasonal heat desiccate these nearly-lifeless terrains.',
   "Deserts usually have a large diurnal and seasonal temperature range, with high daytime temperatures falling sharply at night. The diurnal range may be as much as 20 to 30 °C (36 to 54 °F) and the rock surface experiences even greater temperature differentials. During the day the sky is usually clear and most of the sun's radiation reaches the ground, but as soon as the sun sets, the desert cools quickly by radiating heat into space. In hot deserts, the temperature during daytime can exceed 45 °C (113 °F) in summer and plunge below freezing point at night during winter.",
   'Such large temperature variations have a destructive effect on the exposed rocky surfaces. The repeated fluctuations put a strain on exposed rock and the flanks of mountains crack and shatter. Fragmented strata slide down into the valleys where they continue to break into pieces due to the relentless sun by day and chill by night. Successive strata are exposed to further weathering. The relief of the internal pressure that has built up in rocks that have been underground for aeons can cause them to shatter. Exfoliation also occurs when the outer surfaces of rocks split off in flat flakes. This is believed to be caused by the stresses put on the rock by repeated thermal expansions and contractions which induces fracturing parallel to the original surface. Chemical weathering processes probably play a more important role in deserts than was previously thought. The necessary moisture may be present in the form of dew or mist. Ground water may be drawn to the surface by evaporation and the formation of salt crystals may dislodge rock particles as sand or disintegrate rocks by exfoliation. Shallow caves are sometimes formed at the base of cliffs by this means.',
   'As the desert mountains decay, large areas of shattered rock and rubble occur. The process continues and the end products are either dust or sand. Dust is formed from solidified clay or volcanic deposits whereas sand results from the fragmentation of harder granites, limestone and sandstone. There is a certain critical size (about 0.5 mm) below which further temperature-induced weathering of rocks does not occur and this provides a minimum size for sand grains.']},
 '3': {'cluster_id': 3,
  'cluster_name': 'flowing_unstable',
  'dataset_distribution': {'gutenberg': 209, 'landforms': 10, 'climate': 3},
  'examples': ["A canyon (from Spanish cañón; archaic British English spelling: cañon), gorge or chasm, is a deep cleft between escarpments or cliffs resulting from weathering and the erosive activity of a river over geologic time scales. Rivers have a natural tendency to cut through underlying surfaces, eventually wearing away rock layers as sediments are removed downstream. A river bed will gradually reach a baseline elevation, which is the same elevation as the body of water into which the river drains. The processes of weathering and erosion will form canyons when the river's headwaters and estuary are at significantly different elevations, particularly through regions where softer rock layers are intermingled with harder layers more resistant to weathering.",
   "A canyon may also refer to a rift between two mountain peaks, such as those in ranges including the Rocky Mountains, the Alps, the Himalayas or the Andes. Usually, a river or stream carves out such splits between mountains. Examples of mountain-type canyons are Provo Canyon in Utah or Yosemite Valley in California's Sierra Nevada. Canyons within mountains, or gorges that have an opening on only one side, are called box canyons. Slot canyons are very narrow canyons that often have smooth walls.",
   'The word canyon is Spanish in origin (cañón, pronounced [kaˈɲon]), with the same meaning. The word canyon is generally used in North America, while the words gorge and ravine (French in origin) are used in Europe and Oceania, though gorge and ravine are also used in some parts of North America. In the United States, place names generally use canyon in the southwest (due to their proximity to Spanish-speaking Mexico) and gorge in the northeast (which is closer to French Canada), with the rest of the country graduating between these two according to geography. In Canada, a gorge is usually narrow while a ravine is more open and often wooded. The military-derived word defile is occasionally used in the United Kingdom. In South Africa, kloof (in Krantzkloof Nature Reserve) is used along with canyon (as in Blyde River Canyon) and gorge (in Oribi Gorge).',
   'Sometimes large rivers run through canyons as the result of gradual geological uplift. These are called entrenched rivers, because they are unable to easily alter their course. In the United States, the Colorado River in the Southwest and the Snake River in the Northwest are two examples of tectonic uplift.',
   'A box canyon is a small canyon that is generally shorter and narrower than a river canyon, with steep walls on three sides, allowing access and egress only through the mouth of the canyon. Box canyons were frequently used in the western United States as convenient corrals, with their entrances fenced.',
   'The Yarlung Tsangpo Grand Canyon (or Tsangpo Canyon), along the Yarlung Tsangpo River in Tibet, China, is regarded by some as the deepest canyon on Earth at 5,500 metres (18,000 ft). It is slightly longer than Grand Canyon in the United States. Others consider the Kali Gandaki Gorge in midwest Nepal to be the deepest canyon, with a 6,400-metre (21,000 ft) difference between the level of the river and the peaks surrounding it.',
   "Grand Canyon of northern Arizona in the United States, with an average depth of 1,600 metres (5,200 ft) and a volume of 4.17 trillion cubic metres (147 trillion cubic feet), is one of the world's largest canyons. It was among the 28 finalists of the New 7 Wonders of Nature worldwide poll. (Some referred to it as one of the seven natural wonders of the world.)",
   "Some canyons have notable cultural significance. Evidence of archaic humans has been discovered in Africa's Olduvai Gorge. In the southwestern United States, canyons are important archeologically because of the many cliff-dwellings built in such areas, largely by the ancient Pueblo people who were their first inhabitants."]},
 '4': {'cluster_id': 4,
  'cluster_name': 'rocky_vertical',
  'dataset_distribution': {'gutenberg': 205, 'landforms': 27, 'climate': 2},
  'examples': ['Other xerophytic plants have developed similar strategies by a process known as convergent evolution. They limit water loss by reducing the size and number of stomata, by having waxy coatings and hairy or tiny leaves. Some are deciduous, shedding their leaves in the driest season, and others curl their leaves up to reduce transpiration. Others, such as aloes, store water in succulent leaves or stems or in fleshy tubers.',

In [15]:
with open(API_OUTPUTS_DIR / "cluster_examples.json", "w", encoding="utf-8") as f:
    json.dump(cluster_examples, f, ensure_ascii=False, indent=2)

print("Saved:", API_OUTPUTS_DIR / "cluster_examples.json")

Saved: /Users/apple/Desktop/UCL/skills/python3/data/api_outputs/cluster_examples.json

In [16]:
design_schema = {
    "name": "cluster_design_translation",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "cluster_id": {"type": "integer"},
            "cluster_name": {"type": "string"},
            "semantic_summary": {"type": "string"},
            "openness": {"type": "integer", "minimum": 1, "maximum": 10},
            "verticality": {"type": "integer", "minimum": 1, "maximum": 10},
            "roughness": {"type": "integer", "minimum": 1, "maximum": 10},
            "density": {"type": "integer", "minimum": 1, "maximum": 10},
            "motion_intensity": {"type": "integer", "minimum": 1, "maximum": 10},
            "fragmentation": {"type": "integer", "minimum": 1, "maximum": 10},
            "surface_continuity": {"type": "integer", "minimum": 1, "maximum": 10},
            "material_impression": {"type": "string"},
            "atmosphere_keywords": {
                "type": "array",
                "items": {"type": "string"}
            },
            "tonal_direction": {"type": "string"},
            "image_prompt": {"type": "string"},
            "td_texture_prompt": {"type": "string"},
            "blender_fragment_prompt": {"type": "string"}
        },
        "required": [
            "cluster_id",
            "cluster_name",
            "semantic_summary",
            "openness",
            "verticality",
            "roughness",
            "density",
            "motion_intensity",
            "fragmentation",
            "surface_continuity",
            "material_impression",
            "atmosphere_keywords",
            "tonal_direction",
            "image_prompt",
            "td_texture_prompt",
            "blender_fragment_prompt"
        ],
        "additionalProperties": False
    }
}

In [17]:
def build_cluster_prompt(cluster_payload: dict) -> str:
    cluster_id = cluster_payload["cluster_id"]
    cluster_name = cluster_payload["cluster_name"]
    examples = cluster_payload["examples"]
    dataset_distribution = cluster_payload["dataset_distribution"]

    example_block = "\n\n".join(
        [f"Example {i+1}: {txt}" for i, txt in enumerate(examples)]
    )

    prompt = f"""
You are helping translate clustered environmental language into structured design parameters for a data-driven 3D design workflow.

Cluster ID: {cluster_id}
Cluster Name: {cluster_name}
Dataset Distribution: {dataset_distribution}

Below are representative text examples from this cluster:

{example_block}

Your task:
1. Identify the dominant environmental and spatial qualities in these texts.
2. Summarise the semantic character of the cluster.
3. Translate the cluster into numerical design parameters from 1 to 10.
4. Generate one concise abstract image prompt for grayscale / terrain-like visual generation.
5. Generate one prompt specifically for TouchDesigner texture generation.
6. Generate one prompt specifically for Blender fragment generation.

Important constraints:
- Focus on spatial and material qualities, not narrative plot.
- Keep the output suitable for abstract architectural fragment design.
- Avoid mentioning people, characters, or literary storytelling.
- The image prompt should favour abstract, monochrome, environmental texture.
- The TouchDesigner prompt should describe texture logic, contrast, erosion, flow, grain, or density.
- The Blender prompt should describe fragment form, height variation, edge character, density, and continuity.
"""
    return prompt.strip()

In [24]:
import json

def translate_cluster_with_openai(cluster_payload: dict, model_name="gpt-4.1-mini"):
    prompt = build_cluster_prompt(cluster_payload)

    response = client.responses.create(
        model=model_name,
        input=[
            {
                "role": "system",
                "content": [
                    {
                        "type": "input_text",
                        "text": "Return only valid JSON that matches the provided schema."
                    }
                ]
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": prompt
                    }
                ]
            }
        ],
        text={
            "format": {
                "type": "json_schema",
                "name": design_schema["name"],
                "schema": design_schema["schema"],
                "strict": True
            }
        }
    )

    print(response.output_text)
    return json.loads(response.output_text)

In [19]:
test_cluster = cluster_examples["0"]
print(build_cluster_prompt(test_cluster)[:1500])

You are helping translate clustered environmental language into structured design parameters for a data-driven 3D design workflow.

Cluster ID: 0
Cluster Name: dry_exposed
Dataset Distribution: {'landforms': 146, 'climate': 11, 'gutenberg': 3}

Below are representative text examples from this cluster:

Example 1: Cave-inhabiting animals are often categorized as troglobites (cave-limited species), troglophiles (species that can live their entire lives in caves, but also occur in other environments), trogloxenes (species that use caves, but cannot complete their life cycle fully in caves) and accidentals (animals not in one of the previous categories). Some authors use separate terminology for aquatic forms (for example, stygobites, stygophiles, and stygoxenes).

Example 2: Of these animals, the troglobites are perhaps the most unusual organisms. Troglobitic species often show a number of characteristics, termed troglomorphic, associated with their adaptation to subterranean life. These characteristics may include a loss of pigment (often resulting in a pale or white coloration), a loss of eyes (or at least of optical functionality), an elongation of appendages, and an enhancement of other senses (such as the ability to sense vibrations in water). Aquatic troglobites (or stygobites), such as the endangered Alabama cave shrimp, live in bodies of water found in caves and get nutrients from detritus washed into their caves and from the feces of bats and other cave inhabitants. Oth

In [21]:
import os
from dotenv import load_dotenv
from pathlib import Path

PROJECT_ROOT = Path("/Users/apple/Desktop/UCL/skills/python3")
load_dotenv(PROJECT_ROOT / ".env", override=True)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

print("Loaded?", OPENAI_API_KEY is not None)
print("Prefix:", OPENAI_API_KEY[:12] if OPENAI_API_KEY else None)
print("Suffix:", OPENAI_API_KEY[-8:] if OPENAI_API_KEY else None)
print("Length:", len(OPENAI_API_KEY) if OPENAI_API_KEY else None)

Loaded? True
Prefix: sk-proj--VsW
Suffix: QGfASpIA
Length: 164

In [22]:
from openai import OpenAI

client = OpenAI(api_key=OPENAI_API_KEY)

response = client.responses.create(
    model="gpt-4.1-mini",
    input="Reply with exactly: API test successful."
)

print(response.output_text)

API test successful.

In [25]:
test_cluster = cluster_examples["0"]
print(build_cluster_prompt(test_cluster)[:1200])

You are helping translate clustered environmental language into structured design parameters for a data-driven 3D design workflow.

Cluster ID: 0
Cluster Name: dry_exposed
Dataset Distribution: {'landforms': 146, 'climate': 11, 'gutenberg': 3}

Below are representative text examples from this cluster:

Example 1: Cave-inhabiting animals are often categorized as troglobites (cave-limited species), troglophiles (species that can live their entire lives in caves, but also occur in other environments), trogloxenes (species that use caves, but cannot complete their life cycle fully in caves) and accidentals (animals not in one of the previous categories). Some authors use separate terminology for aquatic forms (for example, stygobites, stygophiles, and stygoxenes).

Example 2: Of these animals, the troglobites are perhaps the most unusual organisms. Troglobitic species often show a number of characteristics, termed troglomorphic, associated with their adaptation to subterranean life. These characteristics may include a loss of pigment (often resulting in a pale or white coloration), a loss of eyes (or at least of optical functionality), an elongation of appendages, and an enhancement of

In [26]:
test_result = translate_cluster_with_openai(test_cluster)
test_result

{"cluster_id":0,"cluster_name":"dry_exposed","semantic_summary":"This cluster represents environments characterized by exposed, fragile geological and biological formations, such as caves and coral reefs, emphasizing delicate structural textures, mineral and biological remnants, and dynamic surface continuity shaped by water erosion and sedimentation processes. The spatial qualities suggest intricate open cavities and complex surfaces with varying verticality but overall low density, highlighting fragile, rough, and eroded textures typical of dry-exposed subterranean and marine ecosystems.","openness":7,"verticality":6,"roughness":8,"density":3,"motion_intensity":4,"fragmentation":7,"surface_continuity":5,"material_impression":"mineral crusts, calcium carbonate exoskeletons, eroded rock, biogenic structures","atmosphere_keywords":["fragile","eroded","textured","delicate","subterranean","marine","exposed","complex"],"tonal_direction":"mid-high contrast grayscale emphasizing texture depth and relief","image_prompt":"abstract monochrome terrain with irregular eroded rock formations, porous textures, and layered mineral crusts forming intricate open cavities and delicate rough surfaces","td_texture_prompt":"high contrast grayscale texture with flowing erosion patterns, granular surface noise, intermittent density of porous holes and layered sediment accumulation; emphasizes slow organic flow and crisp rough edges","blender_fragment_prompt":"cluster of fragmented architectural elements with moderate height variation and rough, jagged edges; sparse but complex distribution creating partial surface continuity and interruptions; forms evoke eroded mineral deposits and biological exoskeleton remnants"}

{'cluster_id': 0,
 'cluster_name': 'dry_exposed',
 'semantic_summary': 'This cluster represents environments characterized by exposed, fragile geological and biological formations, such as caves and coral reefs, emphasizing delicate structural textures, mineral and biological remnants, and dynamic surface continuity shaped by water erosion and sedimentation processes. The spatial qualities suggest intricate open cavities and complex surfaces with varying verticality but overall low density, highlighting fragile, rough, and eroded textures typical of dry-exposed subterranean and marine ecosystems.',
 'openness': 7,
 'verticality': 6,
 'roughness': 8,
 'density': 3,
 'motion_intensity': 4,
 'fragmentation': 7,
 'surface_continuity': 5,
 'material_impression': 'mineral crusts, calcium carbonate exoskeletons, eroded rock, biogenic structures',
 'atmosphere_keywords': ['fragile',
  'eroded',
  'textured',
  'delicate',
  'subterranean',
  'marine',
  'exposed',
  'complex'],
 'tonal_direction': 'mid-high contrast grayscale emphasizing texture depth and relief',
 'image_prompt': 'abstract monochrome terrain with irregular eroded rock formations, porous textures, and layered mineral crusts forming intricate open cavities and delicate rough surfaces',
 'td_texture_prompt': 'high contrast grayscale texture with flowing erosion patterns, granular surface noise, intermittent density of porous holes and layered sediment accumulation; emphasizes slow organic flow and crisp rough edges',
 'blender_fragment_prompt': 'cluster of fragmented architectural elements with moderate height variation and rough, jagged edges; sparse but complex distribution creating partial surface continuity and interruptions; forms evoke eroded mineral deposits and biological exoskeleton remnants'}

In [27]:
cluster_design_outputs = {}

for cluster_key, cluster_payload in cluster_examples.items():
    print(f"Processing cluster {cluster_key} ...")
    try:
        result = translate_cluster_with_openai(cluster_payload)
        cluster_design_outputs[cluster_key] = result
        print("Done:", cluster_payload["cluster_name"])
    except Exception as e:
        print("Error on cluster", cluster_key, e)

Processing cluster 0 ...
{"cluster_id":0,"cluster_name":"dry_exposed","semantic_summary":"This cluster characterizes environments that are predominantly dry or exposed surfaces featuring rugged terrain and complex microhabitats, ranging from cave interiors to coral reef structures. Dominant qualities include porous, coarse textures with notable surface fragmentation and varied verticality due to geological and biological formations. The atmosphere suggests isolation, fragility, and exposure to natural erosive processes.","openness":4,"verticality":7,"roughness":8,"density":5,"motion_intensity":2,"fragmentation":7,"surface_continuity":4,"material_impression":"porous carbonate rock and dry cavernous substrate","atmosphere_keywords":["fragile","isolated","exposed","textured","weathered"],"tonal_direction":"muted monochrome with high texture contrast","image_prompt":"abstract grayscale terrain showing rugged, porous surfaces with deep fissures and fragmented, layered structures reminiscent of dry caves and exposed coral frameworks","td_texture_prompt":"high contrast erosion pattern with layered granular flow simulating dry, cracked surfaces and delicate porous textures, moderate grain density with irregular fragmentation","blender_fragment_prompt":"dense cluster of varied height fragments with sharp, irregular edges and broken continuity, simulating dry, exposed rock formations and fragmented coral shapes with moderate vertical variation and complex overlaps"}
Done: dry_exposed
Processing cluster 1 ...
{"cluster_id":1,"cluster_name":"frozen_quiet","semantic_summary":"An expansive, stark environment characterized by vast open spaces, minimal surface texture, and a quiet, austere atmospheric tone. The terrain is predominantly flat or gently undulating with sparse, fragmented features that evoke dryness and barrenness. The overall feeling is one of isolation and subtle rhythmic patterns shaped by natural erosion and wind, emphasizing spatial openness and surface continuity with low vertical variation.","openness":9,"verticality":2,"roughness":3,"density":2,"motion_intensity":1,"fragmentation":3,"surface_continuity":7,"material_impression":"dry, granular, powdery sand and stone surfaces with occasional cracked earth or sparse rocky outcrops","atmosphere_keywords":["dry","quiet","bleak","isolated","expansive","stillness","barren"],"tonal_direction":"monochrome grayscale with soft contrasts and subtle gradients","image_prompt":"vast monochrome desert terrain with gentle undulations and minimal rocky fragments, emphasizing open space and subtle surface textures, abstract and grainy","td_texture_prompt":"generate sparse granular texture with low contrast, slow erosion flow patterns, fine grain density, subtle wind-driven ripple effects, and minimal fracturing areas","blender_fragment_prompt":"create low-height uneven terrain fragments with soft rounded edges, low density sparse clusters of broken plates, smooth surface continuity, slight elevation variation under 2 units, and gently eroded borders"}
Done: frozen_quiet
Processing cluster 2 ...
{"cluster_id":2,"cluster_name":"lush_dense","semantic_summary":"The cluster characterizes extreme arid desert environments with dominant features including expansive barren rock surfaces, fragmented strata, cracked and shattered rocky terrains resulting from large diurnal and seasonal temperature variations. These spaces are sparsely vegetated or lifeless, exhibiting high surface roughness due to exfoliation and thermal weathering. Spatial qualities comprise broad flat or gently undulating plains, salt flats and playas, interspersed with broken rock fragments and rubble fields. The atmosphere conveys dryness, harshness, and an austere, desolate serenity with strong winds shaping surface textures and sediment distribution.","openness":9,"verticality":3,"roughness":9,"density":2,"motion_intensity":4,"fragmentation":8,"surface_continuity":3,"material_impression":"predominantly mineral, salt crusts, fragmented rock and sand with crystalline and dusty granular surfaces","atmosphere_keywords":["arid","desolate","barren","dry","harsh","wind-swept","thermal stress","fragmented","saline crust"],"tonal_direction":"high contrast grayscale with sharp edges and scattered midtone granular noise","image_prompt":"abstract monochrome terrain of cracked and fractured rock surfaces with salt flats and scattered rubble, high contrast shadows emphasizing rough textures and fragmented strata, vast desolate openness with subtle gradients of granular dust","td_texture_prompt":"generate high contrast erosion patterns with sharp grain boundaries, simulate dry cracked surfaces with dense fine grain distribution, include flow-like sediment displacement lines and salt crust textures, emphasize contrast between smooth playas and coarse fractured rock fields","blender_fragment_prompt":"create dense fields of irregular flat fragmented slabs with sharp jagged edges, moderate height variation simulating exfoliated rock flakes, sparse vertical fractures, low overall continuity with loose assembly, scattered accumulation mimicking thermal stress breakdown and collapsed strata"}
Done: lush_dense
Processing cluster 3 ...
{"cluster_id":3,"cluster_name":"flowing_unstable","semantic_summary":"Deep, narrow, and unstable landforms shaped by erosive flowing water, characterized by steep, fragmented vertical cliffs with strong contrast between hard and soft materials, presenting jagged, irregular edges and dynamic, irregular surface continuity shaped by geological uplift and erosion over time.","openness":2,"verticality":9,"roughness":8,"density":4,"motion_intensity":7,"fragmentation":8,"surface_continuity":3,"material_impression":"rocky, layered, eroded stone with varying hardness and occasional sediment layers","atmosphere_keywords":["deep","narrow","steep","rugged","eroded","dynamic","fragmented","unstable","textured"],"tonal_direction":"high contrast grayscale with stark light and shadow to emphasize depth and roughness","image_prompt":"abstract monochrome terrain of a deep, narrow canyon with steep, jagged cliffs and flowing river paths carving vertical rock faces, emphasizing rough, eroded textures and dramatic shadow gradients","td_texture_prompt":"high contrast procedural erosion texture simulating flowing water carving through layered rock with grainy sediment deposition, strong vertical flow patterns, dynamic roughness, and fragmented surface details","blender_fragment_prompt":"fragmented vertical rock forms with high height variation and sharp, irregular edges, arranged with moderate density and low surface continuity to evoke unstable canyon walls carved by intense erosion and tectonic uplift"}
Done: flowing_unstable
Processing cluster 4 ...
{"cluster_id":4,"cluster_name":"rocky_vertical","semantic_summary":"The cluster centers on harsh, rocky, and vertical environments characterized by rugged terrain, exposed rock surfaces, sparse vegetation adapted to arid or cold climates, and structured landforms such as terraces, caves, and soil patches within extreme ecosystems like deserts and tundras.","openness":3,"verticality":8,"roughness":9,"density":3,"motion_intensity":2,"fragmentation":8,"surface_continuity":2,"material_impression":"rocky, granular, weathered stone with occasional moss or lichen textures","atmosphere_keywords":["barren","rugged","sparse vegetation","eroded","textured","desolate","verticality","harsh environment"],"tonal_direction":"high contrast grayscale with strong shadows and highlights accentuating vertical facets and rough surfaces","image_prompt":"Abstract terrain of rugged vertical rock faces with sharp jagged edges, deep crevices and sparse patches of moss-like texture, monochrome grayscale emphasizing high contrast erosion and vertical depth.","td_texture_prompt":"Generate a high contrast procedural texture of cracked, eroded rock layers with granular grain and sparse organic overlays; emphasize vertical erosion flow lines with moderate density and fragmented surface continuity.","blender_fragment_prompt":"Create fragmented vertical rock formations with high height variation, sharp angular edges, irregular clustering with low density patches; maintain discontinuous surface flow and weathered stone material impression."}
Done: rocky_vertical
Processing cluster 5 ...
{"cluster_id":5,"cluster_name":"atmospheric_abstract","semantic_summary":"This cluster captures the spatial and material essence of arid desert environments defined by minimal precipitation, sparse vegetation, and exposed surfaces shaped by erosion, temperature variation, and wind-driven processes. The terrain is characterized by fragmented rock formations, smooth stones, sand dunes, salt pans, and ephemeral water bodies, creating a dynamic mosaic of textures that exhibit roughness from weathering, low verticality except for occasional dunes or rock outcrops, and a predominantly open, flat spatial quality. The atmosphere conveys dryness, extreme contrast between light and shadow, suspended particulate matter like dust and sand, and an overall sense of starkness and fragmentation.","openness":9,"verticality":3,"roughness":7,"density":2,"motion_intensity":4,"fragmentation":8,"surface_continuity":3,"material_impression":"dry, eroded stone, sand, cracked earth, salt crust","atmosphere_keywords":["arid","dusty","eroded","fragmented","bleached","stark","dry","weathered"],"tonal_direction":"high contrast grayscale with emphasis on texture variations","image_prompt":"Abstract grayscale aerial terrain depicting vast, open arid landscape with scattered fragmented rock pavements, smooth dunes, cracked dry earth, and salt flats under stark lighting creating high contrast textures and shadows.","td_texture_prompt":"High-contrast texture featuring granular sand flow patterns, intermittent smooth stone mosaics, crackled dry earth patches, and sparse salt crust overlays with subtle erosion and dust particle simulation creating dynamic density variations.","blender_fragment_prompt":"Generate low to moderate height fragmented rock and sand fragments with rough edges, varying density and strong discontinuities, interspersed with flat cracked ground planes and sparse salt pan features, emphasizing unevenness and weathered surfaces in a loosely clustered layout."}
Done: atmospheric_abstract

In [28]:
with open(API_OUTPUTS_DIR / "cluster_design_parameters.json", "w", encoding="utf-8") as f:
    json.dump(cluster_design_outputs, f, ensure_ascii=False, indent=2)

print("Saved:", API_OUTPUTS_DIR / "cluster_design_parameters.json")

Saved: /Users/apple/Desktop/UCL/skills/python3/data/api_outputs/cluster_design_parameters.json

In [29]:
rows = []

for k, v in cluster_design_outputs.items():
    row = v.copy()
    row["atmosphere_keywords"] = ", ".join(v.get("atmosphere_keywords", []))
    rows.append(row)

cluster_params_df = pd.DataFrame(rows)
cluster_params_df

,cluster_id,cluster_name,semantic_summary,openness,verticality,roughness,density,motion_intensity,fragmentation,surface_continuity,material_impression,atmosphere_keywords,tonal_direction,image_prompt,td_texture_prompt,blender_fragment_prompt
0,0,dry_exposed,This cluster characterizes environments that a...,4,7,8,5,2,7,4,porous carbonate rock and dry cavernous substrate,"fragile, isolated, exposed, textured, weathered",muted monochrome with high texture contrast,"abstract grayscale terrain showing rugged, por...",high contrast erosion pattern with layered gra...,dense cluster of varied height fragments with ...
1,1,frozen_quiet,"An expansive, stark environment characterized ...",9,2,3,2,1,3,7,"dry, granular, powdery sand and stone surfaces...","dry, quiet, bleak, isolated, expansive, stilln...",monochrome grayscale with soft contrasts and s...,vast monochrome desert terrain with gentle und...,generate sparse granular texture with low cont...,create low-height uneven terrain fragments wit...
2,2,lush_dense,The cluster characterizes extreme arid desert ...,9,3,9,2,4,8,3,"predominantly mineral, salt crusts, fragmented...","arid, desolate, barren, dry, harsh, wind-swept...",high contrast grayscale with sharp edges and s...,abstract monochrome terrain of cracked and fra...,generate high contrast erosion patterns with s...,create dense fields of irregular flat fragment...
3,3,flowing_unstable,"Deep, narrow, and unstable landforms shaped by...",2,9,8,4,7,8,3,"rocky, layered, eroded stone with varying hard...","deep, narrow, steep, rugged, eroded, dynamic, ...",high contrast grayscale with stark light and s...,"abstract monochrome terrain of a deep, narrow ...",high contrast procedural erosion texture simul...,fragmented vertical rock forms with high heigh...
4,4,rocky_vertical,"The cluster centers on harsh, rocky, and verti...",3,8,9,3,2,8,2,"rocky, granular, weathered stone with occasion...","barren, rugged, sparse vegetation, eroded, tex...",high contrast grayscale with strong shadows an...,Abstract terrain of rugged vertical rock faces...,Generate a high contrast procedural texture of...,Create fragmented vertical rock formations wit...
5,5,atmospheric_abstract,This cluster captures the spatial and material...,9,3,7,2,4,8,3,"dry, eroded stone, sand, cracked earth, salt c...","arid, dusty, eroded, fragmented, bleached, sta...",high contrast grayscale with emphasis on textu...,Abstract grayscale aerial terrain depicting va...,High-contrast texture featuring granular sand ...,Generate low to moderate height fragmented roc...

In [30]:
cluster_params_df.to_csv(API_OUTPUTS_DIR / "cluster_parameters_flat.csv", index=False)
print("Saved:", API_OUTPUTS_DIR / "cluster_parameters_flat.csv")

Saved: /Users/apple/Desktop/UCL/skills/python3/data/api_outputs/cluster_parameters_flat.csv

In [31]:
cluster_prompts_df = cluster_params_df[[
    "cluster_id",
    "cluster_name",
    "image_prompt",
    "td_texture_prompt",
    "blender_fragment_prompt"
]].copy()

cluster_prompts_df.to_csv(API_OUTPUTS_DIR / "cluster_prompts.csv", index=False)
print("Saved:", API_OUTPUTS_DIR / "cluster_prompts.csv")
cluster_prompts_df

Saved: /Users/apple/Desktop/UCL/skills/python3/data/api_outputs/cluster_prompts.csv

,cluster_id,cluster_name,image_prompt,td_texture_prompt,blender_fragment_prompt
0,0,dry_exposed,"abstract grayscale terrain showing rugged, por...",high contrast erosion pattern with layered gra...,dense cluster of varied height fragments with ...
1,1,frozen_quiet,vast monochrome desert terrain with gentle und...,generate sparse granular texture with low cont...,create low-height uneven terrain fragments wit...
2,2,lush_dense,abstract monochrome terrain of cracked and fra...,generate high contrast erosion patterns with s...,create dense fields of irregular flat fragment...
3,3,flowing_unstable,"abstract monochrome terrain of a deep, narrow ...",high contrast procedural erosion texture simul...,fragmented vertical rock forms with high heigh...
4,4,rocky_vertical,Abstract terrain of rugged vertical rock faces...,Generate a high contrast procedural texture of...,Create fragmented vertical rock formations wit...
5,5,atmospheric_abstract,Abstract grayscale aerial terrain depicting va...,High-contrast texture featuring granular sand ...,Generate low to moderate height fragmented roc...

In [32]:
cluster_prompts_df = pd.read_csv(API_OUTPUTS_DIR / "cluster_prompts.csv")
cluster_prompts_df

,cluster_id,cluster_name,image_prompt,td_texture_prompt,blender_fragment_prompt
0,0,dry_exposed,"abstract grayscale terrain showing rugged, por...",high contrast erosion pattern with layered gra...,dense cluster of varied height fragments with ...
1,1,frozen_quiet,vast monochrome desert terrain with gentle und...,generate sparse granular texture with low cont...,create low-height uneven terrain fragments wit...
2,2,lush_dense,abstract monochrome terrain of cracked and fra...,generate high contrast erosion patterns with s...,create dense fields of irregular flat fragment...
3,3,flowing_unstable,"abstract monochrome terrain of a deep, narrow ...",high contrast procedural erosion texture simul...,fragmented vertical rock forms with high heigh...
4,4,rocky_vertical,Abstract terrain of rugged vertical rock faces...,Generate a high contrast procedural texture of...,Create fragmented vertical rock formations wit...
5,5,atmospheric_abstract,Abstract grayscale aerial terrain depicting va...,High-contrast texture featuring granular sand ...,Generate low to moderate height fragmented roc...

In [33]:
cluster_prompts_df[["cluster_name", "td_texture_prompt", "blender_fragment_prompt"]]

,cluster_name,td_texture_prompt,blender_fragment_prompt
0,dry_exposed,high contrast erosion pattern with layered gra...,dense cluster of varied height fragments with ...
1,frozen_quiet,generate sparse granular texture with low cont...,create low-height uneven terrain fragments wit...
2,lush_dense,generate high contrast erosion patterns with s...,create dense fields of irregular flat fragment...
3,flowing_unstable,high contrast procedural erosion texture simul...,fragmented vertical rock forms with high heigh...
4,rocky_vertical,Generate a high contrast procedural texture of...,Create fragmented vertical rock formations wit...
5,atmospheric_abstract,High-contrast texture featuring granular sand ...,Generate low to moderate height fragmented roc...

In [34]:
selected_clusters = cluster_prompts_df[
    cluster_prompts_df["cluster_name"].isin([
        "dry_exposed",
        "flowing_unstable",
        "rocky_vertical"
    ])
]
selected_clusters

,cluster_id,cluster_name,image_prompt,td_texture_prompt,blender_fragment_prompt
0,0,dry_exposed,"abstract grayscale terrain showing rugged, por...",high contrast erosion pattern with layered gra...,dense cluster of varied height fragments with ...
3,3,flowing_unstable,"abstract monochrome terrain of a deep, narrow ...",high contrast procedural erosion texture simul...,fragmented vertical rock forms with high heigh...
4,4,rocky_vertical,Abstract terrain of rugged vertical rock faces...,Generate a high contrast procedural texture of...,Create fragmented vertical rock formations wit...